import { AppProps } from 'next/app';
import Head from 'next/head';
import './styles.scss';
import {
  wrapper,
  setDefaultToken,
  fetchListAddressConfig,
  saveUserInfo,
  isWeb,
} from '@nxseo/function-shares';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { ToastContainer } from 'react-toastify';
import { useDispatch } from 'react-redux';
import { Storage } from '@capacitor/storage';
import { Loading, TabBottom } from '@nxseo/ui-shares';

function App({ Component, pageProps }: AppProps) {
  const AnyComponent = Component;
  const route = useRouter();
  const dispatch = useDispatch();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function checkToken() {
      const token = await Storage.get({
        key: 'token',
      });
      const profile = await Storage.get({ key: 'profile' });
      if (token.value && profile.value) {
        setDefaultToken(token.value);
        dispatch(
          saveUserInfo({
            token: token.value,
            profile: JSON.parse(profile.value),
          })
        );
      }
      setLoading(false);
      fetchListAddressConfig();
    }
    checkToken();
  }, [dispatch]);

  return (
    <>
      <Head>
      <title>Chạy cái đi trời</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="target-densitydpi=device-dpi, initial-scale=1.0, user-scalable=no"
        />
        <meta property="og:title" content={"test"} key="title" />
        <meta property="og:description" content={"test cái"} />
        <meta
          property="og:image"
          content={
            "https://gamek.mediacdn.vn/133514250583805952/2021/1/15/1-16106966278281009206635.jpg"
          }
        />
      </Head>
      <main className="app">
        {!loading ? <AnyComponent {...pageProps} /> : <Loading />}
        <ToastContainer
          hideProgressBar
          theme="colored"
          position="top-center"
          autoClose={3000}
          closeOnClick
        />
      </main>
    </>
  );
}

// export default App;
export default wrapper.withRedux(App);
